node_num: "627010"
ami:
  host: "127.0.0.1"
  user: "admin"
  pass: "40318b527dfa"
porcupine_ppn: /usr/local/asl_ai/porcupine/Jarvis_es.ppn
vosk_model: /usr/local/asl_aivosk/vosk-model-small-es-0.42
sounds_dir: /var/lib/asterisk/sounds
google_credentials: /usr/local/asl_ai/credentials/google_tts.json
listen_rate: 16000
chunk: 1024
openweather_key: "c4657af02b7446b14dfbfd3be23ff474"
chatgpt_key: "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"
web_port: 8080
